#baseURL: "https://zaarzetlite.github.io/fs"

baseURL: ""
languageCode: en-us
title: "New Hugo site"
theme: "PaperMod"

menu:
  main:
    - name: Home
      pageRef: /home
      weight: 10
    - name: Products
      pageRef: /products
      weight: 20
    - name: Services
      pageRef: /services
      weight: 30
    - name: Drafts
      pageRef: /drafts/default_draft
      weight: 40

